runtime: php83

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  static_dir: css

- url: /custom/css
  static_dir: custom/css

- url: /custom/js
  static_dir: custom/js

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /js/foundation
  static_dir: js/foundation

- url: /js/vendor
  static_dir: js/vendor

- url: /resources
  static_dir: resources

- url: /fonts
  static_dir: fonts

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /
  static_files: index.html
  upload: index.html

- url: /humans.txt
  static_files: humans.txt
  upload: humans.txt